# Load packages

In [1]:
import os
import numpy as np
import pandas as pd
import scanpy as sc
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
import infercnvpy as cnv
import matplotlib

import sys
sys.path.append("/home/augusta/storage3/augusta/insituCNV/InSituCNV")
import insitucnv as icv

/home/augusta/anaconda3/envs/insitucnv_env/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Load data

In [3]:
import spatialdata as sd

sdata = sd.read_zarr('/home/augusta/storage3/augusta/insituCNV/InSituCNV/Validation/1105_BL.zarr')

version mismatch: detected: RasterFormatV02, requested: FormatV04

In [4]:
sdata

SpatialData object, with associated Zarr store: /home/augusta/storage3/augusta/insituCNV/InSituCNV/Validation/1105_BL.zarr
├── Images
│     └── 'morphology_focus': DataTree[cyx] (4, 30655, 8788), (4, 15327, 4394), (4, 7663, 2197), (4, 3831, 1098), (4, 1915, 549)
├── Labels
│     ├── 'cell_labels': DataTree[yx] (30655, 8788), (15327, 4394), (7663, 2197), (3831, 1098), (1915, 549)
│     └── 'nucleus_labels': DataTree[yx] (30655, 8788), (15327, 4394), (7663, 2197), (3831, 1098), (1915, 549)
├── Points
│     └── 'transcripts': DataFrame with shape: (<Delayed>, 13) (3D points)
├── Shapes
│     ├── 'cell_boundaries': GeoDataFrame shape: (31059, 1) (2D shapes)
│     ├── 'cell_circles': GeoDataFrame shape: (31059, 2) (2D shapes)
│     └── 'nucleus_boundaries': GeoDataFrame shape: (30848, 1) (2D shapes)
└── Tables
      └── 'table': AnnData (30944, 5097)
with coordinate systems:
    ▸ 'global', with elements:
        morphology_focus (Images), cell_labels (Labels), nucleus_labels (Labels), transcripts (Points), cell_boundaries (Shapes), cell_circles (Shapes), nucleus_boundaries (Shapes)

In [5]:
adata = sdata.table

In [6]:
adata

AnnData object with n_obs × n_vars = 30944 × 5097
    obs: 'cell_id', 'transcript_counts', 'control_probe_counts', 'genomic_control_counts', 'control_codeword_counts', 'unassigned_codeword_counts', 'deprecated_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'nucleus_count', 'segmentation_method', 'region', 'z_level', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'n_counts', 'leiden', 'leiden_res0.2', 'leiden_res0.5', 'leiden_res1.0', 'leiden_res1.5', 'leiden_res2.0', 'cell_type', 'status'
    var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'n_cells'
    uns: 'cell_type_colors', 'leiden', 'leiden_colors', 'leiden_res0.2', 'leiden_res0.2_colors', 'leiden_res0.5', 'leiden_res0.5_colors', 'leiden_res1.0', 'leiden_res1.0_colors', 'leiden_res1.5', 'leiden_res1.5_colors', 'leiden_res2.0', 'leiden_res2.0_colors', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'spatialdata_attrs', 'status_colors', 'umap'
    obsm: 'X_pca', 'X_umap', 'spatial'
    varm: 'PCs'
    layers: 'log_norm', 'raw_counts'
    obsp: 'connectivities', 'distances'

In [ ]:
adata.write('/home/augusta/borka_storage/insituCNV/1105_BL.h5ad', compression = 'gzip')

In [2]:
adata=sc.read('/home/augusta/borka_storage/insituCNV/1105_BL.h5ad')

In [7]:
adata

AnnData object with n_obs × n_vars = 30944 × 5097
    obs: 'cell_id', 'transcript_counts', 'control_probe_counts', 'genomic_control_counts', 'control_codeword_counts', 'unassigned_codeword_counts', 'deprecated_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'nucleus_count', 'segmentation_method', 'region', 'z_level', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'n_counts', 'leiden', 'leiden_res0.2', 'leiden_res0.5', 'leiden_res1.0', 'leiden_res1.5', 'leiden_res2.0', 'cell_type', 'status'
    var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'n_cells'
    uns: 'cell_type_colors', 'leiden', 'leiden_colors', 'leiden_res0.2', 'leiden_res0.2_colors', 'leiden_res0.5', 'leiden_res0.5_colors', 'leiden_res1.0', 'leiden_res1.0_colors', 'leiden_res1.5', 'leiden_res1.5_colors', 'leiden_res2.0', 'leiden_res2.0_colors', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'spatialdata_attrs', 'status_colors', 'umap'
    obsm: 'X_pca', 'X_umap', 'spatial'
    varm: 'PCs'
    layers: 'log_norm', 'raw_counts'
    obsp: 'connectivities', 'distances'

In [8]:
print(adata.layers['raw_counts'])

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 10471794 stored elements and shape (30944, 5097)>
  Coords	Values
  (0, 5)	1.0
  (0, 17)	3.0
  (0, 27)	1.0
  (0, 41)	1.0
  (0, 56)	2.0
  (0, 58)	2.0
  (0, 62)	2.0
  (0, 67)	1.0
  (0, 71)	1.0
  (0, 75)	1.0
  (0, 77)	1.0
  (0, 88)	1.0
  (0, 103)	1.0
  (0, 109)	1.0
  (0, 140)	1.0
  (0, 142)	1.0
  (0, 145)	1.0
  (0, 162)	1.0
  (0, 164)	2.0
  (0, 165)	1.0
  (0, 179)	1.0
  (0, 182)	1.0
  (0, 185)	1.0
  (0, 189)	1.0
  (0, 202)	4.0
  :	:
  (30943, 3210)	1.0
  (30943, 3330)	1.0
  (30943, 3365)	2.0
  (30943, 3536)	1.0
  (30943, 3572)	2.0
  (30943, 3600)	1.0
  (30943, 3709)	1.0
  (30943, 3714)	1.0
  (30943, 3833)	2.0
  (30943, 3858)	1.0
  (30943, 3865)	2.0
  (30943, 3972)	1.0
  (30943, 4220)	1.0
  (30943, 4297)	1.0
  (30943, 4306)	1.0
  (30943, 4338)	1.0
  (30943, 4378)	1.0
  (30943, 4407)	1.0
  (30943, 4447)	1.0
  (30943, 4456)	1.0
  (30943, 4567)	1.0
  (30943, 4707)	2.0
  (30943, 4801)	1.0
  (30943, 4845)	1.0
  (30943, 5008)	1.0

# In Situ CNV inference

### Can't smooth the data since copyKAT takes raw counts as input

### CNV inference (copyKAT)

In [9]:
!R

R version 4.5.1 (2025-06-13) -- "Great Square Root"
Copyright (C) 2025 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

>
>
>

In [10]:
adata.obs["normal"] = adata.obs["status"] == "normal"

In [12]:
adata.obs.head(5)

,cell_id,transcript_counts,control_probe_counts,genomic_control_counts,control_codeword_counts,unassigned_codeword_counts,deprecated_codeword_counts,total_counts,cell_area,nucleus_area,...,n_counts,leiden,leiden_res0.2,leiden_res0.5,leiden_res1.0,leiden_res1.5,leiden_res2.0,cell_type,status,normal
0,aaaagjbk-1,910,0,0,0,0,2,910.0,81.461878,24.926251,...,910.0,0,0,0,0,0,0,Epithelial tumor cells (HER2+),tumor,False
1,aaachmja-1,727,0,0,0,0,2,727.0,68.366565,14.991876,...,727.0,0,0,0,0,3,4,Epithelial tumor cells (HER2+),tumor,False
2,aaaeabhb-1,522,0,0,0,0,1,522.0,56.038908,22.036251,...,522.0,1,0,0,1,2,5,Epithelial tumor cells (HER2+),tumor,False
8,aaaipmhe-1,346,0,0,0,0,0,346.0,60.373908,31.428751,...,346.0,3,0,2,3,3,6,Epithelial tumor cells (HER2+),tumor,False
9,aaajopgl-1,1188,0,1,0,0,3,1188.0,108.375004,23.165157,...,1188.0,1,0,0,1,2,5,Epithelial tumor cells (HER2+),tumor,False

In [13]:
cnv.tl.copykat(adata,
               gene_ids="S", 
               min_genes_chr=5, 
               window_size=25, 
               segmentation_cut=0.1, 
               s_name="copykat_result", 
               distance="euclidean", 
               norm_cell_names="normal",
               n_jobs=4
               )

[1] "running copykat v1.1.0"
[1] "step1: read and filter data ..."
[1] "5097 genes, 30944 cells in raw data"
[1] "filtered out 10192 cells with less than min.gene.per.cell; remaining 20814 cells"
[1] "2575 genes past LOW.DR filtering"
[1] "WARNING: low data quality; assigned LOW.DR to UP.DR..."
[1] "step 2: annotations gene coordinates ..."
[1] "start annotation ..."
[1] "step 3: smoothing data with dlm ..."
[1] "step 4: measuring baselines ..."
number of iterations= 1694
number of iterations= 593
number of iterations= 640
number of iterations= 263
number of iterations= 456
number of iterations= 371
[1] "low confidence in classification"
[1] "cell: 1"
WARNING! NOT CONVERGENT!
number of iterations= 500
[1] "cell: 2"
number of iterations= 421
[1] "cell: 3"
WARNING! NOT CONVERGENT!
number of iterations= 500
[1] "cell: 4"
number of iterations= 417
[1] "cell: 5"
WARNING! NOT CONVERGENT!
number of iterations= 500
[1] "cell: 6"
WARNING! NOT CONVERGENT!
number of iterations= 500
[1] "cell: 7"
number of iterations= 281
[1] "step 5: segmentation..."
[1] "too few breakpoints detected; decreased KS.cut to 50%"
[1] "step 6: convert to genomic bins..."
[1] "step 7: adjust baseline ..."
[1] "step 8: final prediction ..."
[1] "step 9: saving results..."
[1] "step 10: ploting heatmap ..."
Time difference of 12.6826 mins

In [14]:
adata

AnnData object with n_obs × n_vars = 30944 × 5097
    obs: 'cell_id', 'transcript_counts', 'control_probe_counts', 'genomic_control_counts', 'control_codeword_counts', 'unassigned_codeword_counts', 'deprecated_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'nucleus_count', 'segmentation_method', 'region', 'z_level', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'n_counts', 'leiden', 'leiden_res0.2', 'leiden_res0.5', 'leiden_res1.0', 'leiden_res1.5', 'leiden_res2.0', 'cell_type', 'status', 'normal', 'cnv'
    var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'n_cells'
    uns: 'cell_type_colors', 'leiden', 'leiden_colors', 'leiden_res0.2', 'leiden_res0.2_colors', 'leiden_res0.5', 'leiden_res0.5_colors', 'leiden_res1.0', 'leiden_res1.0_colors', 'leiden_res1.5', 'leiden_res1.5_colors', 'leiden_res2.0', 'leiden_res2.0_colors', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'spatialdata_attrs', 'status_colors', 'umap', 'cnv'
    obsm: 'X_pca', 'X_umap', 'spatial', 'X_cnv'
    varm: 'PCs'
    layers: 'log_norm', 'raw_counts'
    obsp: 'connectivities', 'distances'

In [15]:
adata.obs.dtypes

cell_id                          object
transcript_counts                 int64
control_probe_counts              int64
genomic_control_counts            int64
control_codeword_counts           int64
unassigned_codeword_counts        int64
deprecated_codeword_counts        int64
total_counts                    float32
cell_area                       float64
nucleus_area                    float64
nucleus_count                   float64
segmentation_method            category
region                         category
z_level                         float64
n_genes_by_counts                 int32
log1p_n_genes_by_counts         float64
log1p_total_counts              float32
pct_counts_in_top_50_genes      float64
pct_counts_in_top_100_genes     float64
pct_counts_in_top_200_genes     float64
pct_counts_in_top_500_genes     float64
n_counts                        float32
leiden                         category
leiden_res0.2                  category
leiden_res0.5                  category
leiden_res1.0                  category
leiden_res1.5                  category
leiden_res2.0                  category
cell_type                      category
status                         category
normal                             bool
cnv                              object
dtype: object

In [20]:
adata.obsm['X_cnv']

array([[-2147483648, -2147483648, -2147483648, ..., -2147483648,
        -2147483648, -2147483648],
       [-2147483648, -2147483648, -2147483648, ..., -2147483648,
        -2147483648, -2147483648],
       [-2147483648, -2147483648, -2147483648, ..., -2147483648,
        -2147483648, -2147483648],
       ...,
       [-2147483648, -2147483648, -2147483648, ..., -2147483648,
        -2147483648, -2147483648],
       [-2147483648, -2147483648, -2147483648, ..., -2147483648,
        -2147483648, -2147483648],
       [-2147483648, -2147483648, -2147483648, ..., -2147483648,
        -2147483648, -2147483648]], shape=(30944, 12167))

In [16]:
del adata.obs["cnv"]  # or whichever column has dtype object

In [17]:
adata.write('/home/augusta/borka_storage/insituCNV/1105_BL_CNV_copyKAT.h5ad', compression = 'gzip')

In [20]:
adata

AnnData object with n_obs × n_vars = 30944 × 5097
    obs: 'cell_id', 'transcript_counts', 'control_probe_counts', 'genomic_control_counts', 'control_codeword_counts', 'unassigned_codeword_counts', 'deprecated_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'nucleus_count', 'segmentation_method', 'region', 'z_level', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'n_counts', 'leiden', 'leiden_res0.2', 'leiden_res0.5', 'leiden_res1.0', 'leiden_res1.5', 'leiden_res2.0', 'cell_type', 'status'
    var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'n_cells'
    uns: 'cell_type_colors', 'leiden', 'leiden_colors', 'leiden_res0.2', 'leiden_res0.2_colors', 'leiden_res0.5', 'leiden_res0.5_colors', 'leiden_res1.0', 'leiden_res1.0_colors', 'leiden_res1.5', 'leiden_res1.5_colors', 'leiden_res2.0', 'leiden_res2.0_colors', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'spatialdata_attrs', 'status_colors', 'umap', 'cnv'
    obsm: 'X_pca', 'X_umap', 'spatial', 'X_cnv'
    varm: 'PCs'
    layers: 'log_norm', 'raw_counts'
    obsp: 'connectivities', 'distances'

In [17]:
adata.obsm['X_cnv'].shape

(30944, 12167)

In [25]:
adata.uns['cnv']

{'chr_pos': {'chr1': 1,
  'chr2': 954,
  'chr3': 1992,
  'chr4': 2867,
  'chr5': 3705,
  'chr6': 4487,
  'chr7': 5211,
  'chr8': 5857,
  'chr9': 6492,
  'chr10': 6972,
  'chr11': 7533,
  'chr12': 8101,
  'chr13': 8676,
  'chr14': 9107,
  'chr15': 9498,
  'chr16': 9830,
  'chr17': 10140,
  'chr18': 10451,
  'chr19': 10787,
  'chr20': 11007,
  'chr21': 11273,
  'chr22': 11422,
  'chr23': 11561}}

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [27]:
adata.var

,gene_ids,feature_types,genome,n_cells_by_counts,mean_counts,log1p_mean_counts,pct_dropout_by_counts,total_counts,log1p_total_counts,n_cells
A2ML1,ENSG00000166535,Gene Expression,Unknown,176,0.005763,0.005747,99.433337,179.0,5.192957,176
AAMP,ENSG00000127837,Gene Expression,Unknown,4680,0.192311,0.175894,84.931904,5973.0,8.695172,4680
AAR2,ENSG00000131043,Gene Expression,Unknown,1474,0.051096,0.049834,95.254194,1587.0,7.370231,1474
AARSD1,ENSG00000266967,Gene Expression,Unknown,1083,0.037059,0.036388,96.513088,1151.0,7.049255,1083
ABAT,ENSG00000183044,Gene Expression,Unknown,680,0.022860,0.022602,97.810619,710.0,6.566672,680
...,...,...,...,...,...,...,...,...,...,...
ZSCAN26,ENSG00000197062,Gene Expression,Unknown,1127,0.038668,0.037939,96.371422,1201.0,7.091742,1127
ZSWIM6,ENSG00000130449,Gene Expression,Unknown,659,0.022184,0.021941,97.878232,689.0,6.536692,659
ZUP1,ENSG00000153975,Gene Expression,Unknown,1410,0.048263,0.047134,95.460253,1499.0,7.313221,1410
ZYG11B,ENSG00000162378,Gene Expression,Unknown,1440,0.048746,0.047595,95.363663,1514.0,7.323171,1440
ZYX,ENSG00000159840,Gene Expression,Unknown,8902,0.438810,0.363816,71.338420,13629.0,9.520028,8902